config/routes.rb
Rails.application.routes.draw do
  #for nested?
  # resources :users do
  #   resources :posts
  # end
  # patch 'posts/:post_id/comments/:id' => 'comments#update'
  # delete 'posts/:post_id/comments/:id' => 'comments#destroy'
  # get 'posts/:post_id/comments' => 'comments#show', as: :comments
  # post 'posts/:post_id/comments' => 'comments#create', as: :new_comment

  resources :posts do
    resources :comments, except: [:index]
  end

  # sign up page with form:
  get 'users/posts' => 'users#user_posts', as: :user
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :profile

  # create (post) action for when sign up form is submitted:
  post 'users/' => 'users#create'
  #posts_paths
  # get 'users/:user_id/posts' => 'posts#index', as: :posts
  # get 'users/:user_id/posts/new' => 'posts#new', as: :new_post
  # get 'users/:user_id/posts/:id' => 'posts#show', as: :post
  # get 'users/:user_id/posts/:id/edit' => 'posts#edit', as: :edit_post
  # post 'users/:user_id/posts' => 'posts#create'
  # patch 'users/:user_id/posts/:id' => 'posts#update'
  # delete 'users/:user_id/posts/:id' => 'posts#destroy'

  get 'pages/secret'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  root to: 'users#welcome'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable

  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]




  def show
  end

  def new
    @comment = @post.comments.new
  end

  def edit
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    # @comment = current_user.comments.new(comment_params)
    # @comment.post = @post

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div>
  <% @post.comments.each do |comment| %>

    <h6><%= link_to comment.user.username, user_path(comment.user) %> commented <%= time_ago_in_words(comment.created_at) %> ago: </h6>
    <div style="border:solid 1px white;margin-top:none">

      <!-- #coming soon: Upvote function -->
      <!-- Upvotes : <%# comment.get_upvotes.size %>
      Downvotes : <%# comment.get_downvotes.size %> -->
    <%= comment.content %>
    <% if current_user == comment.user %>
    <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete%> |
      <%= link_to 'Edit', post_comment_path(@post, comment), method: :patch %>
    <%end%>
    </div>
  <% end %>
</div>

<br>

New Comment:
<%= form_for [@post, @comment] do |f| %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/comments/_view.html.erb
<% @post.comments.each do |comment| %>
Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to comment.user.username, user_path(@comment.user) %>
<div>
  <%=comment.content  %>
</div>
<% end %>