config/routes.rb
Rails.application.routes.draw do
  #for nested?
  # resources :users do
  #   resources :posts
  # end
  # patch 'posts/:post_id/comments/:id' => 'comments#update'
  # delete 'posts/:post_id/comments/:id' => 'comments#destroy'
  # get 'posts/:post_id/comments' => 'comments#show', as: :comments
  # post 'posts/:post_id/comments' => 'comments#create', as: :new_comment

  resources :posts do
    resources :comments, except: [:index]
  end

  # sign up page with form:
  get 'users/posts' => 'users#user_posts', as: :user
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :profile

  # create (post) action for when sign up form is submitted:
  post 'users/' => 'users#create'
  #posts_paths
  # get 'users/:user_id/posts' => 'posts#index', as: :posts
  # get 'users/:user_id/posts/new' => 'posts#new', as: :new_post
  # get 'users/:user_id/posts/:id' => 'posts#show', as: :post
  # get 'users/:user_id/posts/:id/edit' => 'posts#edit', as: :edit_post
  # post 'users/:user_id/posts' => 'posts#create'
  # patch 'users/:user_id/posts/:id' => 'posts#update'
  # delete 'users/:user_id/posts/:id' => 'posts#destroy'

  get 'pages/secret'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  root to: 'users#welcome'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


end

app/views/partials/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
  </div>

  <br>

  <div class="field">
    <%= f.label :content %>
    <br>
    <%= f.text_area :content, :cols => "80", :rows => '8' %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="brandspace" href="#">
        <img alt="DotaJunkie" id="logo" src="https://pbs.twimg.com/profile_images/808475349671493632/nvi7WJf4.jpg">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- use js/jquery to dom get url, and then set it into the current -->
        <li class="active"><a href="#">DotaJunkie<span class="sr-only">(current)</span></a></li>
        <li><a href="/posts">Home</a></li>
        <!-- more dropdown menus, links, search function to come! -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Coming Soon <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search (Coming Soon)">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul id="navRight" class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><a href="#"></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Hello, #{current_user.username}" %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"><%= "#{current_user.username}'s Profile" %></a></li>
            <li><%= link_to 'My Posts', user_path %></li>
            <li><a href="#"><%= link_to 'New Post', new_post_path %></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#"><%= link_to 'Log Out', logout_path, method: :delete %></a></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to 'Log In', login_path %></li>
        <li><%= link_to 'Sign Up', new_user_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>