config/routes.rb
Rails.application.routes.draw do
  #for nested?
  # resources :users do
  #   resources :posts
  # end
  # patch 'posts/:post_id/comments/:id' => 'comments#update'
  # delete 'posts/:post_id/comments/:id' => 'comments#destroy'
  # get 'posts/:post_id/comments' => 'comments#show', as: :comments
  # post 'posts/:post_id/comments' => 'comments#create', as: :new_comment

  resources :posts do
    resources :comments, except: [:index]
  end

  # sign up page with form:
  get 'users/posts' => 'users#user_posts', as: :user
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :profile

  # create (post) action for when sign up form is submitted:
  post 'users/' => 'users#create'
  #posts_paths
  # get 'users/:user_id/posts' => 'posts#index', as: :posts
  # get 'users/:user_id/posts/new' => 'posts#new', as: :new_post
  # get 'users/:user_id/posts/:id' => 'posts#show', as: :post
  # get 'users/:user_id/posts/:id/edit' => 'posts#edit', as: :edit_post
  # post 'users/:user_id/posts' => 'posts#create'
  # patch 'users/:user_id/posts/:id' => 'posts#update'
  # delete 'users/:user_id/posts/:id' => 'posts#destroy'

  get 'pages/secret'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  root to: 'users#welcome'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("updated_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new



  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create


      @post = current_user.posts.new(post_params)



    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    #Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'partials/form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- <h1>DotaJunkie</h1> -->

<!-- <div id="DotaImageHeader"> -->
<!-- <img src="http://cdn.dota2.com/apps/dota2/images/blogfiles/bg_thebetaisover.jpg" alt="Dota Official" id="mainDotaImage"> -->
<!-- </div> -->

<% @posts.each do |post| %>
  <!-- <h2><%=post.title %></h2> -->
  <h2><%= link_to post.title, post_path(post) %></h2>

  Posted <%= time_ago_in_words(post.created_at) %> ago by <%= link_to post.user.username, user_path %>


  <!-- #stretchgoal: add upvote function -->
  <%# if (current_user.voted_for? post) == false %>
  <%# button_to "Upvote!",  :onclick => post.liked_by(current_user) %>
  <%# button_to "Downvote.", :onclick => post.downvote_from(current_user) %>
  <%# end %>
<!--
  Upvotes : <%# post.get_upvotes.size %>
  Downvotes : <%# post.get_downvotes.size %>
  <br> -->



  <p>
    <div>
      <%# image_tag post.image_url, width: '500px' if post.image_url.present? %>
    </div>
    <%# post.content %>
  </p>
  <hr>
<% end %>

<% if current_user %>
<%= link_to 'New Post', new_post_path %>
<%end%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'partials/form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>
  <!-- <strong>Title:</strong> -->
  <strong><%= @post.title %></strong>

  <!-- #coming soon: upvote function -->
  <!-- Upvotes : <%# @post.get_upvotes.size %>
  Downvotes : <%# @post.get_downvotes.size %>
   -->
</h1>

  Posted <%= time_ago_in_words(@post.created_at) %> ago by <%= link_to @post.user.username, user_path(@post.user) %>

<br>
<br>

<p>
  <!-- <strong>Content:</strong> -->
  <%= @post.content %>
</p>


<% if current_user == @post.user %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%end%>
<%= link_to 'Back', posts_path %>

<br>

<!-- <%= render 'comments/view' %> -->
<%= render 'comments/form'%>